on: push
jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    ports: 
    - "3001:3001"
    expose:
    - 3001
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: murisocrates/brightstarts:${{ github.run_number }}